/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Axt (https://sketchfab.com/shooter24994)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/uranus-4d2f0c3674904472ac413fdabbf491d7
title: Uranus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "react-three-fiber"
import useStore from './store'
import { Redirect } from 'react-router'

export default function PLanet(props) {
  const group = useRef()
  const ring = useRef()
  const { nodes, materials } = useGLTF('/Space Explorer/planet/scene.gltf')

  const nextlevel = useStore((state) => state.nextlevel)
  const setNextLevel = useStore((state) => state.setNextLevel)

  useFrame(() => {
    group.current.position.z += 0.1;
    // group.current.scale.x += 0.0008;
    // group.current.scale.y += 0.0008;
    // group.current.scale.z += 0.0008;

    if(group.current.position.z > -0.02) {
      // group.current.position.z = -180;
      setNextLevel()
    }
  })


  return (
    <group ref={group} {...props} dispose={null} position={[2,0,-202]} >
      <group rotation={[-Math.PI / 2, 0, 0]} >
        <group position={[0, 0, 0]} rotation={[-Math.PI, 0, Math.PI]} >
          <group rotation={[Math.PI / 2, 2, 0]} >
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
              <mesh material={materials['Material.002']} geometry={nodes.Sphere_Material002_0.geometry} material-transparent material-opacity={1}/>
            </group>
            <group ref={ring} rotation={[-Math.PI / 2, 1.37, 0]} scale={[1.5, 1.5, 1.5]}>
              <mesh material={materials.ring} geometry={nodes.Circle_ring_0.geometry} material-transparent material-opacity={1}/>
            </group>
            <group rotation={[-Math.PI / 2, 1.37, 0]} scale={[1.4, 1.4, 1.4]}>
              <mesh material={materials.ring} geometry={nodes.Circle001_ring_0.geometry} material-transparent material-opacity={1}/>
            </group>
            <group rotation={[-Math.PI / 2, 1.37, 0]} scale={[1.3, 1.3, 1.3]}>
              <mesh material={materials.ring} geometry={nodes.Circle002_ring_0.geometry} material-transparent material-opacity={1}/>
            </group>
          </group>
        </group>
      </group>
     
    </group>
  )
}

useGLTF.preload('/Space Explorer/planet/scene.gltf')
